# Generated by Django 5.1.6 on 2025-08-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiabetesPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Age", models.IntegerField()),
                ("Gender", models.CharField(max_length=10)),
                ("symptoms", models.TextField()),
                ("Polyuria", models.BooleanField(default=False)),
                ("Polydipsia", models.BooleanField(default=False)),
                ("sudden_weight_loss", models.BooleanField(default=False)),
                ("weakness", models.BooleanField(default=False)),
                ("Polyphagia", models.BooleanField(default=False)),
                ("Genital_thrush", models.BooleanField(default=False)),
                ("visual_blurring", models.BooleanField(default=False)),
                ("Itching", models.BooleanField(default=False)),
                ("Irritability", models.BooleanField(default=False)),
                ("delayed_healing", models.BooleanField(default=False)),
                ("partial_paresis", models.BooleanField(default=False)),
                ("muscle_stiffness", models.BooleanField(default=False)),
                ("Alopecia", models.BooleanField(default=False)),
                ("Obesity", models.BooleanField(default=False)),
                ("prediction", models.BooleanField(default=False)),
            ],
        ),
    ]
